import dish_1 from "../assets/home/Image 1.png";
import dish_2 from "../assets/home/Image 2.png";
import dish_3 from "../assets/home/Image 3.png";
import dish_5 from "../assets/home/Image 5.png";
import dish_6 from "../assets/home/Image 6.png";

export const menu_tabs = [
  "hot dishes",
  "cold dishes",
  "soup",
  "grill",
  "appetizer",
  "dessert",
];

const dishes = [
  {
    title: "Spicy seasoned seafood noodles",
    price: 2.29,
    available: 20,
    cover: dish_1,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Spicy seasoned seafood noodles",
    price: 2.29,
    available: 20,
    cover: dish_1,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Spicy seasoned seafood noodles",
    price: 2.29,
    available: 20,
    cover: dish_1,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Spicy seasoned seafood noodles",
    price: 2.29,
    available: 20,
    cover: dish_1,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Spicy seasoned seafood noodles",
    price: 2.29,
    available: 20,
    cover: dish_1,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
  {
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    cover: dish_2,
  },
  {
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    cover: dish_3,
  },
  {
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    cover: dish_5,
  },
  {
    title: "Hot spicy fried rice with omelet",
    price: 3.49,
    available: 13,
    cover: dish_5,
  },
  {
    title: "Spicy instant noodle with special omelette",
    price: 3.59,
    available: 17,
    cover: dish_6,
  },
];

export const all_dishes = dishes.map((dish) => {
  dish.category = menu_tabs[Math.floor(Math.random() * menu_tabs.length)];
  return dish;
});
